#!/bin/bash
tool_cs350_update=`egrep "^update:" ~/tool/cs350/info`
if [ ${#} -eq 1 ] ;then
	cd ${HOME}${tool_cs350_update#update: ~}ASST${1}/
	bmake
	bmake install
else
	echo "Expected The number of Assignment you want to update"
fi
